### ISSUE TITLE
_JAVA_OPTION environment variable breaks json parse

### ISSUE THREAD

**Issue by acbaraka** [sveetch/py-html-checker#22]
```
java -jar c:\users\acbaraka\appdata\local\programs\python\python39\lib\site-packages\html_checker/vnujar/vnu.jar --format json --exit-zero-always --user-agent Validator.nu/LV py-html-checker/0.4.0 C:\test.jhtml
```
Will produce an initial first line:
```
Picked up _JAVA_OPTIONS: -foobar
```
if the _JAVA_OPTIONS environment variable is set. Users can work around this by unsetting the variable but some detection for this might be best in the long run.

**Comment by sveetch** [comment]
What did you expect exactly when you say "some detection for this" ? And does this line breaks the report ?

**Comment by acbaraka** [comment]
Oh let me elaborate more.
I think an if "_JAVA_OPTIONS" in content then remove the first line (from the java captured output) would fix this issue but I defer to you and your design.
So yes, this "picked up _JAVA_OPTIONS" line does break the report as it fails to get just the json dump.

**Comment by sveetch** [comment]
Ok, understood.
