### ISSUE TITLE
pkg_resources is deprecated

### ISSUE THREAD

**Issue by jpmckinney** [sveetch/py-html-checker#26]
> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)).

https://setuptools.pypa.io/en/latest/pkg_resources.html

**Comment by sveetch** [comment]
i will fix this but it will make the package dropping support for Python<3.8

**Comment by sveetch** [comment]
Done in v0.5.0
